package digital.patron.app_patronnativeapp.domain.dto

data class HomeContentsDto(
    val curationThumbnail: List<String>,
    val curationThumbArtworkTitle: List<String>,
    val curationArtistName: List<String>,
    val curationArtistCount: List<Integer>,
    val waitingThumbnail: List<String>,
    val waitingThumbArtworkTitle: List<String>,
    val waitingArtistName: List<String>,
    val waitingArtistCount: List<Integer>,
    val newlyArtworks: List<String>,
    val theme1ExhibitionTitle: String,
    val theme1Thumbnail: List<String>,
    val theme1ThumbArtworkTitle: List<String>,
    val theme1ThumbArtistTitle: List<String>,
    val theme2ExhibitionTitle: String,
    val theme2Thumbnail: List<String>,
    val theme2ThumbArtworkTitle: List<String>,
    val theme2ThumbArtistTitle: List<String>,
    val theme3ExhibitionTitle: String,
    val theme3Thumbnail: List<String>,
    val theme3ThumbArtworkTitle: List<String>,
    val theme3ThumbArtistTitle: List<String>,
    val theme4ExhibitionTitle: String,
    val theme4Thumbnail: List<String>,
    val theme4ThumbArtworkTitle: List<String>,
    val theme4ThumbArtistTitle: List<String>,
    val theme5ExhibitionTitle: String,
    val theme5Thumbnail: List<String>,
    val theme5ThumbArtworkTitle: List<String>,
    val theme5ThumbArtistTitle: List<String>,
    val artistProfileImage: List<String>,
    val artistNameRecommend: List<String>,
)
